name: API testing

on:
  push:
  workflow_dispatch:


jobs:
  TestAPI:
    name: Test API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: List directory structure
        run: ls -R

      - name: Run API Tests
        run: |
          mvn  test -Dtest=**/testAPI/*